apiVersion: v1
kind: Service
metadata:
  name: my-smart-rollout-active
spec:
  type: ClusterIP
  selector:
    app: my-smart-rollout
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080